# Generated by Django 5.0 on 2024-04-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_user_is_active_user_is_staff_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='profile_pictures/logo2.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
